source("_Shared.R")
source("_Functions.R")
bringInRequirements()

OUT_TO_DISK <- TRUE

data <- getData("VOD.csv")
data <- data[, !colnames(data) %in% c('Dates')]

if (!OUT_TO_DISK) par(mfrow = c(1, 1), mar = c(18, 5, 2, 1))

if (OUT_TO_DISK) png(filename = "images/Distributions_boxplot.png", width = 8, height = 8, units = "in", res = 400)
boxplot(data, las = 2, main = "Boxplot - Features", ylab = "Normalized values")
if (OUT_TO_DISK) dev.off()

if (!OUT_TO_DISK) par(mfrow = c(2, 2), mar = c(5, 5, 5, 5))
if (OUT_TO_DISK) png(filename = "images/Distributions_EARN_YLD.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$PX_TO_BOOK_RATIO), main = "EARN_YLD", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()

if (OUT_TO_DISK) png(filename = "images/Distributions_EQY_DVD_YLD_12M.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$EQY_DVD_YLD_12M), main = "EQY_DVD_YLD_12M", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_EARN_YLD.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$EARN_YLD), main = "EARN_YLD", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_CASH_FLOW_YIELD.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$CASH_FLOW_YIELD), main = "CASH_FLOW_YIELD", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()

if (OUT_TO_DISK) png(filename = "images/Distributions_PX_TO_SALES_RATIO.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$PX_TO_SALES_RATIO), main = "PX_TO_SALES_RATIO", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_PX_CLOSE_1D.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$PX_CLOSE_1D), main = "PX_CLOSE_1D", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_BASIC_EPS_3YR_AVG_GROWTH.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$BASIC_EPS_3YR_AVG_GROWTH), main = "BASIC_EPS_3YR_AVG_GROWTH", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_EBIT_TO_NET_SALES.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$EBIT_TO_NET_SALES), main = "EBIT_TO_NET_SALES", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()

if (OUT_TO_DISK) png(filename = "images/Distributions_X5_YEAR_AVERAGE_ADJUSTED_ROE.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$X5_YEAR_AVERAGE_ADJUSTED_ROE), main = "X5_YEAR_AVERAGE_ADJUSTED_ROE", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_RETURN.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$RETURN), main = "RETURN", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_STYLE_VALUE.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$STYLE_VALUE), main = "STYLE_VALUE", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_STYLE_QUALITY.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$STYLE_QUALITY), main = "STYLE_QUALITY", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()

if (OUT_TO_DISK) png(filename = "images/Distributions_MOMENTUM_252.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$MOMENTUM_252), main = "MOMENTUM_252", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_MOMENTUM_125.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$MOMENTUM_125), main = "MOMENTUM_125", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_STYLE_GROWTH.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$STYLE_GROWTH), main = "STYLE_GROWTH", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_STYLE_MOMENTUM.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$STYLE_MOMENTUM), main = "STYLE_MOMENTUM", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()

if (OUT_TO_DISK) png(filename = "images/Distributions_LB_MONTHLY_RETURN.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$LB_MONTHLY_RETURN), main = "LB_MONTHLY_RETURN", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_LB_MONTHLY_VOLATILITY.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$LB_MONTHLY_VOLATILITY), main = "LB_MONTHLY_VOLATILITY", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_LF_MONTHLY_RETURN.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$LF_MONTHLY_RETURN), main = "LF_MONTHLY_RETURN", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()
if (OUT_TO_DISK) png(filename = "images/Distributions_LF_MONTHLY_VOLATILITY.png", width = 8, height = 8, units = "in", res = 400)
plot(density(data$LF_MONTHLY_VOLATILITY), main = "LF_MONTHLY_VOLATILITY", col = "blue", lwd = 2)
if (OUT_TO_DISK) dev.off()

